/**
 * POST /api/generate
 *
 * Single-call replacement for the old SI → structure two-step chain.
 * Combines creative narrative direction + block architecture into one cached
 * system prompt. Streams sections as SSE events so the preview builds live.
 *
 * Events:
 *   data: {"type":"section","section":{...}}   — one per completed section
 *   data: {"type":"complete","brief":{...}}    — full PageBrief at the end
 *   data: {"type":"error","error":"..."}       — on failure
 */
import { NextRequest } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import JSON5 from 'json5'
import type { PageBrief, Section } from '../../lib/types'
import { getTemplate, templateToPrompt, applyTemplateOverrides } from '../../lib/templates'
import '../_startup'

// ─── System prompt ────────────────────────────────────────────────────────────

function buildSystemPrompt(): string {
  return `You are a page architect. Fill a product page template with content.

Components:
hero — headline, cta {label, destination}, imageBrief, imageIntent (lifestyle|product|abstract)
proofPoints — headline, items[]: {title, description, icon (IcCheckboxOn|IcStar|IcSecured|IcGlobe|IcHome|IcShoppingBag|IcWifiNetwork|IcHealthy)}
mediaText5050 — headline, body, cta {label, destination}, mediaType (image|none), imageBrief, imageIntent; blockOptions: variant (accordion|paragraphs), paragraphColumnLayout (single|multi)
  accordion: items[]: {subtitle, body}
  single: body field only (no items)
  multi: items[]: {subtitle, body}
carousel — headline, items[]: {title, description}, imageBrief, imageIntent
cardGrid — headline, items[]: {title, description}, imageBrief per item, imageIntent
mediaTextAsymmetric — items[]: {title (question), body (answer)}; blockOptions: variant (faq)

Resolve is appended automatically — do not generate it.

Output valid JSON only:
meta: pageName, slug, audience, primaryAction, keyMessage
sections[]: order, sectionName, component, narrativeRole (setup|engage), imageBrief, imageIntent
  contentSlots: headline, body, cta {label, destination}, mediaType (image|none), items[]
  blockOptions: emphasis, variant, paragraphColumnLayout, imagePosition, imageAspectRatio, cardSize, columns, alignment
status: "draft"
`
}

const SYSTEM_BLOCKS: Anthropic.Messages.TextBlockParam[] = [
  { type: 'text', text: buildSystemPrompt() } as Anthropic.Messages.TextBlockParam & { cache_control: { type: 'ephemeral' } },
]
;(SYSTEM_BLOCKS[0] as Anthropic.Messages.TextBlockParam & { cache_control?: { type: 'ephemeral' } }).cache_control = { type: 'ephemeral' }

// ─── Incremental section extraction ──────────────────────────────────────────

/**
 * Scans the accumulated JSON buffer for complete section objects.
 * Returns any newly completed sections not yet in `seen`.
 */
function extractNewSections(buffer: string, seen: Set<number>): Section[] {
  const match = /"sections"\s*:\s*\[/.exec(buffer)
  if (!match) return []

  const arrayStart = buffer.indexOf('[', match.index)
  if (arrayStart === -1) return []

  const results: Section[] = []
  let depth = 0
  let objStart = -1

  for (let i = arrayStart + 1; i < buffer.length; i++) {
    const c = buffer[i]
    if (c === '{') {
      if (depth === 0) objStart = i
      depth++
    } else if (c === '}') {
      depth--
      if (depth === 0 && objStart !== -1) {
        try {
          const obj = JSON.parse(buffer.slice(objStart, i + 1)) as Section
          if (typeof obj.order === 'number' && !seen.has(obj.order)) {
            seen.add(obj.order)
            results.push(obj)
          }
        } catch {
          // object not yet valid JSON — skip until buffer grows
        }
        objStart = -1
      }
    }
  }

  return results
}

function extractJson(raw: string): string {
  let t = raw.trim().replace(/^\uFEFF/, '')
  const codeBlock = t.match(/```(?:json)?\s*([\s\S]*?)```/)
  if (codeBlock) t = codeBlock[1].trim()
  const first = t.indexOf('{')
  const last = t.lastIndexOf('}')
  if (first !== -1 && last > first) t = t.slice(first, last + 1)
  return t
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, '')
}

function tryParse(t: string): PageBrief | null {
  try { return JSON.parse(t) as PageBrief } catch { /* fall through */ }
  try { return JSON5.parse(t) as PageBrief } catch { /* fall through */ }
  return null
}

// ─── Fixed Resolve template ───────────────────────────────────────────────────

/**
 * Builds the fixed Resolve act sections from brief meta.
 * These are never generated by Claude — always appended by the system.
 * Order numbers start after the last Setup/Engage section.
 */
function buildResolveSections(meta: PageBrief['meta'], startOrder: number, template: import('../../lib/templates').PageTemplate): Section[] {
  const productName = meta.pageName || 'this product'
  const ctaLabel = template.resolveCta.label
  const ctaDestination = template.resolveCta.destination
  const isHardware = template.productType === 'hardware'

  const sections: Section[] = []
  let order = startOrder

  if (isHardware) {
    sections.push({
      order: order++,
      sectionName: 'Why buy with Jio?',
      component: 'cardGrid',
      rationale: 'Trust signals for hardware purchase. Reinforces delivery, shopping, and support.',
      narrativeRole: 'resolve',
      contentSlots: {
        headline: 'Why buy with Jio?',
        subhead: null,
        body: null,
        cta: null,
        mediaType: 'none',
        items: [
          { title: 'Free delivery', cardType: 'colourIconText', icon: 'IcTruckDelivery' },
          { title: 'Shop at JioMart', cardType: 'colourIconText', icon: 'IcShoppingBag' },
          { title: 'We\'re here for you', cardType: 'colourIconText', icon: 'IcHeadphones' },
        ],
      },
      blockOptions: {
        columns: 3,
        emphasis: 'ghost',
        surfaceColour: null,
        variant: null,
        size: null,
        template: null,
        alignment: null,
        mediaSize: null,
        cardSize: null,
      },
      crossLinks: [],
      flags: [],
      imageBrief: null,
      imageIntent: null,
    })
  }

  sections.push({
    order: order++,
    sectionName: 'Summary statement',
    component: 'mediaTextStacked',
    rationale: 'Single sentence that resolves the narrative arc. No new claims.',
    narrativeRole: 'resolve',
    contentSlots: {
      headline: meta.keyMessage || `${productName} — built for what comes next.`,
      subhead: null,
      body: null,
      cta: null,
      mediaType: 'none',
      items: null,
    },
    blockOptions: {
      template: 'textOnly',
      size: 'editorial',
      emphasis: 'ghost',
      alignment: 'center',
      surfaceColour: null,
      variant: null,
      mediaSize: null,
      cardSize: null,
      columns: null,
    },
    crossLinks: [],
    flags: [],
    imageBrief: null,
    imageIntent: null,
  })

  sections.push({
    order: order++,
    sectionName: 'Keep exploring',
    component: 'cardGrid',
    rationale: 'Related products and resources. Keeps users in the Jio ecosystem.',
    narrativeRole: 'resolve',
    contentSlots: {
      headline: 'Keep exploring',
      subhead: null,
      body: null,
      cta: null,
      mediaType: 'none',
      items: [
        { title: 'More Jio devices', description: 'Explore the full range of Jio hardware built for Indian homes.', cardType: 'mediaTextBelow' },
        { title: 'MyJio App', description: 'Manage your Jio services, recharges, and devices in one place.', cardType: 'mediaTextBelow' },
        { title: 'Jio Plans', description: 'Find the right plan to get the most from your Jio products.', cardType: 'mediaTextBelow' },
      ],
    },
    blockOptions: {
      columns: 3,
      emphasis: 'ghost',
      surfaceColour: null,
      variant: null,
      size: null,
      template: null,
      alignment: null,
      mediaSize: null,
      cardSize: null,
    },
    crossLinks: [],
    flags: [],
    imageBrief: null,
    imageIntent: null,
  })

  sections.push({
    order: order++,
    sectionName: 'Purchase CTA',
    component: 'mediaTextStacked',
    rationale: 'Final action. One CTA only. Always last on the page.',
    narrativeRole: 'resolve',
    contentSlots: {
      headline: ctaLabel,
      subhead: null,
      body: meta.keyMessage || null,
      cta: { label: ctaLabel, destination: ctaDestination, rationale: 'Primary conversion action' },
      mediaType: 'none',
      items: null,
    },
    blockOptions: {
      template: 'textOnly',
      size: 'feature',
      emphasis: 'bold',
      alignment: 'center',
      surfaceColour: 'primary',
      variant: null,
      mediaSize: null,
      cardSize: null,
      columns: null,
    },
    crossLinks: [],
    flags: [],
    imageBrief: null,
    imageIntent: null,
  })

  return sections
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    return new Response(
      `data: ${JSON.stringify({ type: 'error', error: 'ANTHROPIC_API_KEY not set' })}\n\n`,
      { status: 500, headers: { 'Content-Type': 'text/event-stream' } }
    )
  }

  const body = await req.json()
  const { productName, whatItDoes = '', whatIsInIt = '', builtFor = '', productType = 'hardware', facts, keyMessage, primaryAction } = body

  if (!productName) {
    return new Response(
      `data: ${JSON.stringify({ type: 'error', error: 'productName required' })}\n\n`,
      { status: 400, headers: { 'Content-Type': 'text/event-stream' } }
    )
  }

  const templateId = productType === 'software' ? 'product-page-software' : 'product-page-hardware'
  const template = getTemplate(templateId)!
  const templateInstructions = templateToPrompt(template)

  // New flow: facts[] array from suggestion loop
  // Legacy flow: whatItDoes / whatIsInIt / builtFor freetext
  const hasFacts = Array.isArray(facts) && facts.length > 0

  const userMessage = hasFacts
    ? `Product: ${productName} (${productType})
${keyMessage ? `Key message: ${keyMessage}` : ''}
${primaryAction ? `Primary action: ${primaryAction}` : ''}

Facts provided by the team:
${facts.map((f: string) => `- ${f}`).join('\n')}

${templateInstructions}

Generate the PageBrief as JSON. Output ONLY the JSON object.`
    : `Product: ${productName}

What it does:
${whatItDoes || '(not provided)'}

What is in it:
${whatIsInIt || '(not provided)'}

Built for:
${builtFor || '(not provided)'}

${templateInstructions}

Generate the PageBrief as JSON. Output ONLY the JSON object.`

  const anthropic = new Anthropic({ apiKey })
  const encoder = new TextEncoder()

  const stream = new ReadableStream({
    async start(controller) {
      const push = (event: Record<string, unknown>) => {
        controller.enqueue(encoder.encode(`data: ${JSON.stringify(event)}\n\n`))
      }

      try {
        let buffer = ''
        const seen = new Set<number>()

        const response = anthropic.messages.stream({
          model: 'claude-haiku-4-5-20251001',
          max_tokens: 5000,
          system: SYSTEM_BLOCKS as Anthropic.Messages.TextBlockParam[],
          messages: [{ role: 'user', content: userMessage }],
        })

        for await (const event of response) {
          if (
            event.type === 'content_block_delta' &&
            event.delta.type === 'text_delta'
          ) {
            buffer += event.delta.text
            const newSections = extractNewSections(buffer, seen)
            for (const section of newSections) {
              push({ type: 'section', section })
            }
          }
        }

        // Parse and emit the complete brief for meta, ia, etc.
        const finalMsg = await response.finalMessage()
        const rawText = finalMsg.content.find(c => c.type === 'text')
        const text = rawText?.type === 'text' ? rawText.text : ''
        const brief = tryParse(extractJson(text))

        if (!brief) {
          console.error('[generate] Failed to parse final brief. First 500 chars:', text.slice(0, 500))
          push({ type: 'error', error: 'Failed to parse page brief' })
        } else {
          brief.meta = brief.meta ?? ({} as PageBrief['meta'])
          brief.ia = brief.ia ?? ({} as PageBrief['ia'])
          brief.sections = Array.isArray(brief.sections) ? brief.sections : []
          brief.meta.template = 'product-page'
          brief.meta.pageName = brief.meta.pageName || productName
          brief.createdAt = new Date().toISOString()
          brief.version = 1
          brief.status = 'draft'

          // Enforce template palette overrides on engage sections
          const briefWithOverrides = applyTemplateOverrides(brief, template)
          Object.assign(brief, briefWithOverrides)

          // Append fixed Resolve template — never generated by Claude
          const nextOrder = brief.sections.reduce((max, s) => Math.max(max, s.order ?? 0), 0) + 1
          const resolveSections = buildResolveSections(brief.meta, nextOrder, template)
          brief.sections = [...brief.sections, ...resolveSections]

          push({ type: 'complete', brief })
        }
      } catch (err) {
        console.error('[generate] Stream error:', err)
        push({ type: 'error', error: err instanceof Error ? err.message : 'Unknown error' })
      } finally {
        controller.close()
      }
    },
  })

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive',
    },
  })
}
