/**
 * Page templates — define the structural skeleton Claude fills in.
 *
 * Setup slots are fixed (Claude provides content, not structure).
 * Engage is a palette — Claude picks blocks from the allowed list.
 * Resolve is always code-appended and never generated by Claude.
 *
 * `overrides` on a palette entry are enforced in briefToBlocks regardless of
 * what Claude outputs. `defaults` carry soft constraints (item counts, caps)
 * also enforced in code. Claude is told about both via templateToPrompt.
 */

import type { PageBrief } from './types'

export type ProductType = 'hardware' | 'software'

export type SetupSlot = {
  component: string
  required: boolean
  hint: string
}

export type PaletteEntry = {
  component: string
  hint: string
  max?: number
  /** Prop values merged into blockOptions in briefToBlocks — Claude cannot override these */
  overrides?: Record<string, unknown>
  /** Soft constraints enforced in briefToBlocks (item counts, caps) */
  defaults?: {
    itemCount?: number  // default number of items if Claude provides none
    maxItems?: number   // hard cap on items array length
  }
}

export type PageTemplate = {
  id: string
  name: string
  productType: ProductType
  /** Drives the purchase CTA label and destination in the Resolve section */
  resolveCta: {
    label: string
    destination: string
  }
  setup: SetupSlot[]
  engage: {
    min: number
    max: number
    /** Ordered by preference — Claude should favour entries listed first */
    palette: PaletteEntry[]
  }
}

// ─── Shared engage palette ────────────────────────────────────────────────────
// All hardware and software product pages use the same block palette.
// Template-specific differences are only in resolveCta.

const PRODUCT_PAGE_PALETTE: PaletteEntry[] = [
  // ── MediaText5050 — three flavors ────────────────────────────────────────
  {
    component: 'mediaText5050',
    hint: 'Accordion — 3 expandable rows. Best for feature detail.',
    overrides: { variant: 'accordion', paragraphColumnLayout: undefined, imagePosition: 'left', imageAspectRatio: '1:1' },
    defaults: { itemCount: 3 },
    max: 2,
  },
  {
    component: 'mediaText5050',
    hint: 'Single paragraph — one subtitle + body. Best for a single focused claim.',
    overrides: { variant: 'paragraphs', paragraphColumnLayout: 'single', imagePosition: 'left', imageAspectRatio: '1:1' },
    max: 3,
  },
  {
    component: 'mediaText5050',
    hint: 'Multi paragraph — 3 subtitle+body pairs. Good for specs or comparisons.',
    overrides: { variant: 'paragraphs', paragraphColumnLayout: 'multi', imagePosition: 'left', imageAspectRatio: '1:1' },
    defaults: { itemCount: 3 },
    max: 2,
  },
  // ── Carousel ─────────────────────────────────────────────────────────────
  {
    component: 'carousel',
    hint: 'Compact carousel — 4 cards. Good for a feature list or accessory range.',
    defaults: { itemCount: 4 },
    max: 1,
  },
  // ── CardGrid ─────────────────────────────────────────────────────────────
  {
    component: 'cardGrid',
    hint: 'Card grid — 3 cards. Good for feature highlights or product comparisons.',
    defaults: { itemCount: 3 },
    max: 2,
  },
  // ── ProofPoints ──────────────────────────────────────────────────────────
  {
    component: 'proofPoints',
    hint: 'Icon strip — 4 trust signals. Use for RTBs, key specs, or use cases.',
    defaults: { itemCount: 4, maxItems: 4 },
    max: 2,
  },
  // ── FAQ ──────────────────────────────────────────────────────────────────
  {
    component: 'mediaTextAsymmetric',
    hint: 'FAQ — 5 questions. Title is always "Questions, answered".',
    overrides: { variant: 'faq' },
    defaults: { itemCount: 5 },
    max: 1,
  },
]

const PRODUCT_PAGE_SETUP: SetupSlot[] = [
  {
    component: 'hero',
    required: true,
    hint: 'Bold opener. One headline that makes a promise. Product or lifestyle image. For hardware: CTA is "Shop on JioMart". For software: CTA is "Download the app".',
  },
  {
    component: 'proofPoints',
    required: false,
    hint: 'Max 4 trust signals. Use only when the product has functional RTBs worth establishing early (specs, compatibility, key differentiators). Skip for purely emotional/lifestyle openers.',
  },
]

// ─── Templates ───────────────────────────────────────────────────────────────

export const TEMPLATES: Record<string, PageTemplate> = {
  'product-page-hardware': {
    id: 'product-page-hardware',
    name: 'Product Page — Hardware',
    productType: 'hardware',
    resolveCta: {
      label: 'Shop on JioMart',
      destination: 'jiomart.com',
    },
    setup: PRODUCT_PAGE_SETUP,
    engage: {
      min: 4,
      max: 7,
      palette: PRODUCT_PAGE_PALETTE,
    },
  },
  'product-page-software': {
    id: 'product-page-software',
    name: 'Product Page — Software / App',
    productType: 'software',
    resolveCta: {
      label: 'Download the app',
      destination: 'apps',
    },
    setup: PRODUCT_PAGE_SETUP,
    engage: {
      min: 4,
      max: 7,
      palette: PRODUCT_PAGE_PALETTE,
    },
  },
}

export function getTemplate(id: string): PageTemplate | null {
  return TEMPLATES[id] ?? null
}

// ─── Override application ─────────────────────────────────────────────────────

/**
 * Apply palette overrides and item caps to a brief's engage sections.
 * Matches each section to the most specific palette entry by component +
 * discriminating blockOptions fields, then merges overrides and caps items.
 */
export function applyTemplateOverrides(brief: PageBrief, template: PageTemplate): PageBrief {
  const palette = template.engage.palette
  const DISCRIMINATORS = ['variant', 'paragraphColumnLayout'] as const

  const sections = brief.sections.map((section) => {
    if (section.narrativeRole !== 'engage') return section

    const candidates = palette.filter((e) => e.component === section.component)
    if (!candidates.length) return section

    const opts = (section.blockOptions ?? {}) as Record<string, unknown>

    // Find the palette entry whose discriminating overrides best match Claude's output
    const match =
      candidates.find((entry) => {
        const ov = entry.overrides ?? {}
        return DISCRIMINATORS.every((k) => {
          if (ov[k] === undefined) return true
          return opts[k] === ov[k] || opts[k] === undefined || opts[k] === null
        })
      }) ?? candidates[0]

    // Merge overrides into blockOptions
    const newBlockOptions = { ...(section.blockOptions ?? {}), ...(match.overrides ?? {}) }

    // Cap items array to maxItems
    const maxItems = match.defaults?.maxItems
    const slots = section.contentSlots
    const newItems =
      maxItems && Array.isArray(slots.items) && slots.items.length > maxItems
        ? slots.items.slice(0, maxItems)
        : slots.items

    return {
      ...section,
      blockOptions: newBlockOptions,
      contentSlots: newItems !== slots.items ? { ...slots, items: newItems } : slots,
    }
  })

  return { ...brief, sections }
}

// ─── Prompt serialisation ─────────────────────────────────────────────────────

export function templateToPrompt(t: PageTemplate): string {
  const setupLines = t.setup
    .map((s, i) => `  ${i + 1}. ${s.component}${s.required ? '' : ' (optional)'} — ${s.hint}`)
    .join('\n')

  const paletteLines = t.engage.palette
    .map((p) => {
      const ov = p.overrides ?? {}
      const ovNote = Object.keys(ov).length
        ? ` [enforced: ${Object.entries(ov).map(([k, v]) => `${k}=${v}`).join(', ')}]`
        : ''
      const defNote = p.defaults?.itemCount ? ` [default ${p.defaults.itemCount} items]` : ''
      const maxItemsNote = p.defaults?.maxItems ? ` [max ${p.defaults.maxItems} items]` : ''
      return `  - ${p.component}${p.max ? ` (max ${p.max}×)` : ''}${ovNote}${defNote}${maxItemsNote}: ${p.hint}`
    })
    .join('\n')

  return `Template: ${t.name}

SETUP (fixed order — provide content for each slot):
${setupLines}

ENGAGE (pick ${t.engage.min}–${t.engage.max} blocks):
${paletteLines}

Do not use components outside this palette.`
}
